# Generated by Django 2.2.4 on 2020-07-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='datos/')),
                ('tamano', models.IntegerField(default=0)),
                ('nombre', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='maestroES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('maestro', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='nodos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EstadoLora', models.BooleanField(default=False)),
                ('NumeroNodo', models.IntegerField(default=0)),
                ('AnchoBanda', models.IntegerField(default=0)),
                ('Corriente', models.IntegerField(default=0)),
                ('PaquetesEnviados', models.IntegerField(default=0)),
                ('PaquetesRecibidos', models.IntegerField(default=0)),
                ('TiempoEnvio', models.FloatField(default=0)),
                ('FuerzaSenal', models.IntegerField(default=0)),
                ('CargaUtil', models.TextField(default=0)),
                ('estadoGnss', models.BooleanField(default=False)),
                ('NumeroSatelites', models.IntegerField(default=0)),
                ('dilucion', models.FloatField(default=0)),
                ('latitud', models.FloatField(default=0)),
                ('longitud', models.FloatField(default=0)),
                ('altitud', models.FloatField(default=0)),
                ('fixQuality', models.IntegerField(default=0)),
            ],
        ),
    ]
