# Generated by Django 2.2.1 on 2019-08-16 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0004_nodos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodos',
            old_name='frecuencia',
            new_name='AnchoBanda',
        ),
        migrations.RenameField(
            model_name='nodos',
            old_name='latencia',
            new_name='Canal',
        ),
        migrations.RenameField(
            model_name='nodos',
            old_name='power',
            new_name='CargaUtil',
        ),
        migrations.RenameField(
            model_name='nodos',
            old_name='satelites',
            new_name='Corriente',
        ),
        migrations.RenameField(
            model_name='nodos',
            old_name='CRC',
            new_name='EstadoLora',
        ),
        migrations.RenameField(
            model_name='nodos',
            old_name='estado',
            new_name='estadoGnss',
        ),
        migrations.RemoveField(
            model_name='nodos',
            name='nombre',
        ),
        migrations.AddField(
            model_name='nodos',
            name='FuerzaSenal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nodos',
            name='NumeroNodo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nodos',
            name='NumeroSatelites',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nodos',
            name='PaquetesEnviados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nodos',
            name='PaquetesRecibidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nodos',
            name='TiempoEnvio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nodos',
            name='dilucion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nodos',
            name='latitud',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nodos',
            name='longitud',
            field=models.IntegerField(default=0),
        ),
    ]
