# Generated by Django 2.2.2 on 2019-06-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0002_auto_20190627_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='nombre',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
