# Generated by Django 2.2.2 on 2019-07-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0003_lista_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='nodos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, max_length=200)),
                ('estado', models.BooleanField(default=False)),
                ('fixQuality', models.IntegerField(default=0)),
                ('satelites', models.IntegerField(default=0)),
                ('latitud', models.TextField(blank=True, max_length=200)),
                ('longitud', models.TextField(blank=True, max_length=200)),
                ('altitud', models.IntegerField(default=0)),
                ('latencia', models.IntegerField(default=0)),
                ('frecuencia', models.IntegerField(default=0)),
                ('power', models.IntegerField(default=0)),
                ('CRC', models.BooleanField(default=False)),
            ],
        ),
    ]
