# Generated by Django 2.2.1 on 2019-08-21 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0005_auto_20190815_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodos',
            name='Canal',
        ),
    ]
