# Generated by Django 2.2.1 on 2019-08-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0006_remove_nodos_canal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodos',
            name='CargaUtil',
            field=models.TextField(default=0),
        ),
    ]
