# Generated by Django 2.2.2 on 2019-11-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0007_auto_20190821_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodos',
            name='altitud',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nodos',
            name='dilucion',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nodos',
            name='latitud',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nodos',
            name='longitud',
            field=models.FloatField(default=0),
        ),
    ]
