# Generated by Django 2.2.2 on 2019-11-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0008_auto_20191118_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodos',
            name='TiempoEnvio',
            field=models.FloatField(default=0),
        ),
    ]
