# Generated by Django 2.2.2 on 2019-11-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0009_auto_20191120_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='maestroES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('maestro', models.BooleanField(default=False)),
            ],
        ),
    ]
